database:
  url: jdbc:postgresql://stg-db-host:5432/training_app
  username: stg_user
  password: stg_password
  driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
