spring:
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration
  redis:
    host: localhost
    port: 6379
  application:
    name: trainingapp
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true   # allow DTO serialization

server:
  servlet:
    context-path: /trainingapp

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

jwt:
  lifetime: 36000000
  keys-path: secret

resilience4j:
  circuitbreaker:
    instances:
      trainerHoursService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      trainerHoursService:
        timeoutDuration: 3s

