database:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  username: sa
  password:
  driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: ${database.driver-class-name}
    hikari:
      maximum-pool-size: 2
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: create-drop  # deleting schema after shutdown
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  activemq:
    broker-url: vm://localhost?broker.persistent=false

  flyway:
    enabled: false  # no migrations for unit/integration tests

