spring:
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    context-path: /trainingapp

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true



